// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: gemini-sls

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_loading
void ui_Screen_loading_screen_init(void);
lv_obj_t *ui_Screen_loading;
lv_obj_t *ui_img_loading_bg;
lv_obj_t *ui_Label_loading;


// SCREEN: ui_Screen_status
void ui_Screen_status_screen_init(void);
lv_obj_t *ui_Screen_status;
lv_obj_t *ui_img_status_bg;
lv_obj_t *ui_TextArea_debug_status;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;


// SCREEN: ui_Screen_AiChat
void ui_Screen_AiChat_screen_init(void);
lv_obj_t *ui_Screen_AiChat;
lv_obj_t *ui_img_chat_bg;
lv_obj_t *ui_TextArea_AI_response;
lv_obj_t *ui_TextArea_chat_input;


// SCREEN: ui_Screen_Menu
void ui_Screen_Menu_screen_init(void);
lv_obj_t *ui_Screen_Menu;
lv_obj_t *ui_img_menu_bg;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Button_reset;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Button_back;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label_info;
lv_obj_t *ui_Label_ip;
lv_obj_t *ui_Bar_Battery;
lv_obj_t *ui_img_mask;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen_loading_screen_init();
ui_Screen_status_screen_init();
ui_Screen_AiChat_screen_init();
ui_Screen_Menu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen_loading);
}
