// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: gemini-sls

#ifndef _GEMINI_SLS_UI_H
#define _GEMINI_SLS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen_loading
void ui_Screen_loading_screen_init(void);
extern lv_obj_t *ui_Screen_loading;
extern lv_obj_t *ui_img_loading_bg;
extern lv_obj_t *ui_Label_loading;
// SCREEN: ui_Screen_status
void ui_Screen_status_screen_init(void);
extern lv_obj_t *ui_Screen_status;
extern lv_obj_t *ui_img_status_bg;
extern lv_obj_t *ui_TextArea_debug_status;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
// SCREEN: ui_Screen_AiChat
void ui_Screen_AiChat_screen_init(void);
extern lv_obj_t *ui_Screen_AiChat;
extern lv_obj_t *ui_img_chat_bg;
extern lv_obj_t *ui_TextArea_AI_response;
extern lv_obj_t *ui_TextArea_chat_input;
// SCREEN: ui_Screen_Menu
void ui_Screen_Menu_screen_init(void);
extern lv_obj_t *ui_Screen_Menu;
extern lv_obj_t *ui_img_menu_bg;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Button_reset;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Button_back;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label_info;
extern lv_obj_t *ui_Label_ip;
extern lv_obj_t *ui_Bar_Battery;
extern lv_obj_t *ui_img_mask;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_loading_bg_png);   // assets/Images/loading bg.png
LV_IMG_DECLARE( ui_img_images_status_bg_png);   // assets/Images/status bg.png
LV_IMG_DECLARE( ui_img_images_chat_bg_png);   // assets/Images/chat bg.png
LV_IMG_DECLARE( ui_img_images_menu_bg_png);   // assets/Images/menu bg.png
LV_IMG_DECLARE( ui_img_images_battery_main_png);   // assets/Images/battery main.png
LV_IMG_DECLARE( ui_img_images_battery_indicator_png);   // assets/Images/battery indicator.png
LV_IMG_DECLARE( ui_img_images_mask_png);   // assets/Images/mask.png


LV_FONT_DECLARE( ui_font_RR17);
LV_FONT_DECLARE( ui_font_RR13);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
