// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: gemini-sls

#include "ui.h"

// void function_keyUp(lv_event_t * e)
// {
// 	// Your code here
// }
