// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: gemini-sls

#include "../ui.h"

void ui_Screen_Menu_screen_init(void)
{
ui_Screen_Menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_Menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_Menu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_menu_bg = lv_img_create(ui_Screen_Menu);
lv_img_set_src(ui_img_menu_bg, &ui_img_images_menu_bg_png);
lv_obj_set_width( ui_img_menu_bg, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_img_menu_bg, LV_SIZE_CONTENT);   /// 135
lv_obj_set_align( ui_img_menu_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_menu_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_menu_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Screen_Menu);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 240);
lv_obj_set_height( ui_Container1, 78);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, 29 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_reset = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_Button_reset, 225);
lv_obj_set_height( ui_Button_reset, 30);
lv_obj_set_x( ui_Button_reset, 0 );
lv_obj_set_y( ui_Button_reset, -17 );
lv_obj_set_align( ui_Button_reset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_reset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_reset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_reset, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_reset, lv_color_hex(0x868686), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_reset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_reset, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_reset, lv_color_hex(0xFF6500), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_Button_reset, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_Button_reset, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Label1 = lv_label_create(ui_Button_reset);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Reset");
lv_obj_set_style_text_font(ui_Label1, &ui_font_RR17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_back = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_Button_back, 225);
lv_obj_set_height( ui_Button_back, 30);
lv_obj_set_x( ui_Button_back, 0 );
lv_obj_set_y( ui_Button_back, -17 );
lv_obj_set_align( ui_Button_back, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_back, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_back, lv_color_hex(0x868686), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_back, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_back, lv_color_hex(0xEB6638), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_back, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Button_back, lv_color_hex(0xFF6500), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_Button_back, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_Button_back, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Label2 = lv_label_create(ui_Button_back);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Back to Chat");
lv_obj_set_style_text_font(ui_Label2, &ui_font_RR17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_info = lv_label_create(ui_Screen_Menu);
lv_obj_set_width( ui_Label_info, 197);
lv_obj_set_height( ui_Label_info, 20);
lv_obj_set_x( ui_Label_info, 0 );
lv_obj_set_y( ui_Label_info, -21 );
lv_obj_set_align( ui_Label_info, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_info,"GeminiPuter");
lv_obj_set_style_text_color(ui_Label_info, lv_color_hex(0x4EBD92), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_info, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_info, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_info, &ui_font_RR17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_ip = lv_label_create(ui_Screen_Menu);
lv_obj_set_width( ui_Label_ip, 156);
lv_obj_set_height( ui_Label_ip, 20);
lv_obj_set_x( ui_Label_ip, -36 );
lv_obj_set_y( ui_Label_ip, -53 );
lv_obj_set_align( ui_Label_ip, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_ip,"...");
lv_obj_set_style_text_align(ui_Label_ip, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ip, &ui_font_RR17, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_Battery = lv_bar_create(ui_Screen_Menu);
lv_obj_set_width( ui_Bar_Battery, 68);
lv_obj_set_height( ui_Bar_Battery, 13);
lv_obj_set_x( ui_Bar_Battery, 79 );
lv_obj_set_y( ui_Bar_Battery, -54 );
lv_obj_set_align( ui_Bar_Battery, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Bar_Battery, &ui_img_images_battery_main_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_Bar_Battery, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Battery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Battery, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Bar_Battery, &ui_img_images_battery_indicator_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Bar_Battery, lv_color_hex(0xFF6500), LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Bar_Battery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_img_mask = lv_img_create(ui_Screen_Menu);
lv_img_set_src(ui_img_mask, &ui_img_images_mask_png);
lv_obj_set_width( ui_img_mask, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_img_mask, LV_SIZE_CONTENT);   /// 8
lv_obj_set_x( ui_img_mask, -108 );
lv_obj_set_y( ui_img_mask, 18 );
lv_obj_set_align( ui_img_mask, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_mask, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_mask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
