// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: gemini-sls

#include "../ui.h"

void ui_Screen_loading_screen_init(void)
{
ui_Screen_loading = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_loading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_loading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_loading_bg = lv_img_create(ui_Screen_loading);
lv_img_set_src(ui_img_loading_bg, &ui_img_images_loading_bg_png);
lv_obj_set_width( ui_img_loading_bg, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_img_loading_bg, LV_SIZE_CONTENT);   /// 135
lv_obj_set_align( ui_img_loading_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_loading_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_loading_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_loading = lv_label_create(ui_Screen_loading);
lv_obj_set_width( ui_Label_loading, 194);
lv_obj_set_height( ui_Label_loading, 23);
lv_obj_set_x( ui_Label_loading, 0 );
lv_obj_set_y( ui_Label_loading, 43 );
lv_obj_set_align( ui_Label_loading, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_loading,"GeminiPuter");
lv_obj_set_style_text_color(ui_Label_loading, lv_color_hex(0xFF6400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_loading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_loading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_loading, &ui_font_RR17, LV_PART_MAIN| LV_STATE_DEFAULT);

}
